import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const supabase = createClient(
  "https://emtnkyfpzryozlzwtqve.supabase.co",
  "sb_publishable_HJuZlWHcqhNs5UyjcQKTZw_MvHxUbld"
);

// The publishable key is safe for browser use; Supabase Row Level Security
// controls what anonymous and signed-in users can access.
const dogs=[['Luna','Australian Shepherd','Medium','High','Loyal and brilliant','https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=700&q=80'],['Milo','Beagle','Small','Medium','Curious and friendly','https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=700&q=80'],['Nova','Labrador Mix','Large','Medium','Gentle family companion','https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=700&q=80'],['Teddy','Pomeranian','Small','Low','Calm and affectionate','https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=700&q=80']];let saved=JSON.parse(localStorage.getItem('pawmatch')||'[]');const cards=document.querySelector('#cards'),modal=document.querySelector('#modal');function score(d){return d[2]==='Small'?92:d[3]==='Medium'?86:78}function render(){let q=search.value.toLowerCase(),s=size.value,e=energy.value;cards.innerHTML=dogs.filter(d=>d.join(' ').toLowerCase().includes(q)&&(!s||d[2]===s)&&(!e||d[3]===e)).map((d,i)=>'<article class="card"><img src="'+d[5]+'" alt="'+d[0]+'"><div><span class="tag">'+d[2]+' · '+d[3]+' energy</span><span class="score">'+score(d)+'% match</span><h3>'+d[0]+'</h3><p>'+d[1]+'<br>'+d[4]+'</p><button data-i="'+i+'">View match →</button></div></article>').join('');document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>show(dogs[b.dataset.i]));favorites.querySelector('b').textContent=saved.length}function show(d){let yes=saved.includes(d[0]);details.innerHTML='<p class="eyebrow">YOUR MATCH</p><h2>'+d[0]+' is a '+score(d)+'% match</h2><p><b>Why:</b> '+d[4]+'. Their '+d[3].toLowerCase()+' energy and '+d[2].toLowerCase()+' size are considered in your compatibility score.</p><button id="save" class="primary">'+(yes?'Saved ♥':'Save '+d[0]+' ♥')+'</button>';modal.showModal();save.onclick=()=>{if(!saved.includes(d[0]))saved.push(d[0]);localStorage.setItem('pawmatch',JSON.stringify(saved));modal.close();render()}}search.oninput=render;size.onchange=energy.onchange=render;document.querySelector('.close').onclick=()=>modal.close();match.onclick=()=>{document.querySelector('#discover').scrollIntoView({behavior:'smooth'});render()};favorites.onclick=()=>alert(saved.length?'Saved dogs: '+saved.join(', '):'No saved dogs yet.');render();